# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d384e158d1edb1dc667b54d93f43c54236adae508db46411e42cd252f49d77c642518b42f40648024f9002ac11399e048327ccf6df87207a535afa6c8fc797fb

test:
  secret_key_base: b5ee0d01b2a584af08b882d6d15d95358854a2aacaa371ed616ef24e62cc0de909c6f8c65b1c0ebf9b6c09a1f452c8902c0d848ddb1042ac31164e9ead728b5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
